### ISSUE TITLE
Schedule Demo Slots for Week 8 - March 28

### ISSUE THREAD

**Issue by colinmurphy01** [18F/fns-snap-qcs#16]
- [ ] Identify users for COTS demos
- [ ] Schedule HOLDs for demos and debriefs (10 slots)

BONUS:
- [ ] Identify vendors for demo
- [ ] Schedule HOLDs for demos with vendor

**Comment by beechnut** [comment]
Oops, looks like I opened a duplicate right after you opened this. I'll close this one since the other one has 5 todo list items instead of 4.
