### ISSUE TITLE
Research synthesis

### ISSUE THREAD

**Issue by lauranash18f** [18F/fns-snap-qcs#46]
Specific forms TBD: eg roles matrix, lifecycle chart, role one-pagers, opportunity tree

Coworking on Mar 23: scope synthesis, that is, have an outline of what materials we want to create for week 8 work sessions & presentations. + Granular divvying.

Mar 24 into Week 8, we can build those out and conduct deeper synthesis.

**Comment by colinmurphy01** [comment]
I think we can call this done for R1? CC @lauranash18f
